import {initial,validate,transform,addStroke,keyboardMove,PALETTES} from './model.mjs';
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d'),KEY='foldlight-v1';let state=initial(),undo=[],redo=[],color=0,draft=null,pen=[.5,.28],pointer=null,keyboard=false;
function say(t){$('#status').textContent=t;}function warning(t){$('#storage').textContent=t;$('#storage').hidden=!t;}
try{const raw=localStorage.getItem(KEY);if(raw){state=validate(JSON.parse(raw));say('Your drawing is ready.');}}catch{warning('Saved drawing unavailable. Download projects to keep a copy.');}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));warning('');}catch{warning('Browser saving is unavailable. Download your project to keep it.');}}
function remember(){undo.push(structuredClone(state));if(undo.length>20)undo.shift();redo=[];}
function change(fn,message){cancelDraft();remember();fn();save();update();say(message);}
function paint(target=ctx,size=canvas.width,showPen=true){target.fillStyle='#0c1921';target.fillRect(0,0,size,size);target.lineCap='round';target.lineJoin='round';for(const stroke of [...state.strokes,...(draft?[{points:draft,color}]:[])]){target.strokeStyle=PALETTES[state.palette][stroke.color];target.fillStyle=target.strokeStyle;target.lineWidth=state.width*size;for(const points of transform(stroke.points,state.mode,state.copies)){if(points.length===1){target.beginPath();target.arc(points[0][0]*size,points[0][1]*size,state.width*size/2,0,Math.PI*2);target.fill();}else{target.beginPath();points.forEach(([x,y],i)=>{i?target.lineTo(x*size,y*size):target.moveTo(x*size,y*size);});target.stroke();}}}if(showPen&&document.activeElement===canvas){target.strokeStyle='#fff';target.lineWidth=1.5;const x=pen[0]*size,y=pen[1]*size;target.beginPath();target.moveTo(x-9,y);target.lineTo(x+9,y);target.moveTo(x,y-9);target.lineTo(x,y+9);target.stroke();}}
function update(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));$('#copies').value=state.copies;$('#copies-value').textContent=state.copies;$('#copies-label').hidden=state.mode!=='rotate';$('#width').value=Math.round(state.width*1000);$('#palette').value=state.palette;$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length;$('#add').disabled=state.strokes.length>=60;$('#drawing-info').textContent=`${state.strokes.length} ${state.strokes.length===1?'stroke':'strokes'} · ${state.mode==='rotate'?`${state.copies} rotations`:state.mode==='mirror'?'four reflections':'3 × 3 tiles'}`;$('#colors').replaceChildren();PALETTES[state.palette].forEach((c,i)=>{const b=document.createElement('button');b.className='swatch';b.style.setProperty('--swatch',c);b.id=`color-${i}`;b.textContent=i===color?'✓':String(i+1);b.setAttribute('aria-label',`Color ${i+1}`);b.setAttribute('aria-pressed',String(i===color));b.onclick=()=>{finishDraft();color=i;update();$(`#color-${i}`).focus();};$('#colors').append(b);});paint();}
function cancelDraft(){draft=null;keyboard=false;pointer=null;paint();}
function finishDraft(){if(!draft)return;const points=draft;draft=null;keyboard=false;pointer=null;try{const next=addStroke(state,points,color);remember();state=next;save();update();say('Stroke added. Undo removes it.');}catch(e){paint();say(e.message);}}
function point(e){const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
canvas.onpointerdown=e=>{if(e.button!==0)return;if(state.strokes.length>=60){say('Paper has 60 strokes. Clear or Undo before adding more.');return;}finishDraft();canvas.focus({preventScroll:true});pointer=e.pointerId;pen=point(e);draft=[pen];canvas.setPointerCapture(e.pointerId);paint();};
canvas.onpointermove=e=>{if(pointer!==e.pointerId||!draft)return;pen=point(e);const last=draft.at(-1);if(draft.length<512&&Math.hypot(pen[0]-last[0],pen[1]-last[1])>.003){draft.push(pen);paint();}};
canvas.onpointerup=e=>{if(pointer===e.pointerId){finishDraft();if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}};canvas.onpointercancel=()=>{cancelDraft();say('Unfinished stroke discarded.');};
canvas.onkeydown=e=>{if(e.key.startsWith('Arrow')){e.preventDefault();pen=keyboardMove(pen,e.key,e.shiftKey);if(keyboard&&draft&&draft.length<512)draft.push(pen);paint();}else if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(keyboard)finishDraft();else if(state.strokes.length>=60)say('Paper has 60 strokes. Clear or Undo first.');else{draft=[pen];keyboard=true;say('Drawing. Move with arrows; Space finishes the stroke.');paint();}}else if(e.key==='Escape'){e.preventDefault();cancelDraft();say('Unfinished stroke discarded.');}};canvas.onfocus=()=>paint();canvas.onblur=()=>{if(keyboard)finishDraft();paint();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.mode!==b.dataset.mode)change(()=>{state.mode=b.dataset.mode;},'Same strokes, new arrangement.');});
$('#copies').oninput=e=>{$('#copies-value').textContent=e.target.value;};$('#copies').onchange=e=>change(()=>{state.copies=+e.target.value;},'Rotations updated.');$('#width').onchange=e=>change(()=>{state.width=+e.target.value/1000;},'Stroke width updated.');$('#palette').onchange=e=>change(()=>{state.palette=e.target.value;},'Palette updated.');
$('#add').onclick=()=>{const n=state.strokes.length,a=(n%7)*.22,r=.14+(n%3)*.07;const points=Array.from({length:22},(_,i)=>{const t=i/21;return [.5+Math.cos(a+t*1.8)*r,.5+Math.sin(a+t*1.8)*r];});change(()=>{state=addStroke(state,points,color);},'Curve added. Draw another, or try a different repeat.');};
$('#undo').onclick=()=>{if(!undo.length)return;cancelDraft();redo.push(structuredClone(state));state=undo.pop();save();update();say('Previous drawing restored.');if($('#undo').disabled)$('#redo').focus();};$('#redo').onclick=()=>{if(!redo.length)return;cancelDraft();undo.push(structuredClone(state));state=redo.pop();save();update();say('Change restored.');if($('#redo').disabled)$('#undo').focus();};$('#clear').onclick=()=>change(()=>{state.strokes=[];},'Paper cleared. Undo brings your drawing back.');
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#png').onclick=()=>{finishDraft();const output=document.createElement('canvas');output.width=output.height=1600;paint(output.getContext('2d'),1600,false);output.toBlob(blob=>{if(blob){download(blob,'foldlight.png');say('1600 × 1600 image downloaded.');}else say('Image could not be saved. Your drawing is intact.');},'image/png');};$('#save').onclick=()=>{finishDraft();download(new Blob([JSON.stringify(state)],{type:'application/json'}),'foldlight.json');say('Editable project downloaded.');};
$('#open').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw new Error('Choose a project smaller than 2 MB.');const next=validate(JSON.parse(await f.text()));change(()=>{state=next;},'Project opened. Undo restores the previous drawing.');}catch(error){say(error.message||'Project could not be opened.');}finally{e.target.value='';}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelDraft();});update();
